import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import { useRouter } from "next/router";
const inter = Inter({ subsets: ["latin"] });
import Link from "next/link";

export default function Home({ viewRoles }) {
  const router = useRouter();
  useEffect(() => {
    if (!localStorage.getItem("token")) {
      router.push("/login");
    }
  }, [router.query]);

  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <div className="bg-blue-900 p-8 from-blue-700 bg-gradient-to-r ">
          <div className="flex flex-col text-center w-full   mt-4 mb-2 ">
            <h1 className="sm:text-4xl text-3xl uppercase font-semibold  title-font  text-white">
              {viewRoles.value}
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed font-normal text-white text-sm">
              CEO
            </p>
          </div>
        </div>

        <div className="mt-8">
          <div className="text-gray-600 body-font">
            <div className="container px-5 py-8  mx-auto ">
              <div className="flex flex-wrap justify-center ">
                <div className="   xl:w-1/5 xl:py-12 lg:w-1/3 md:w-1/3 px-4 py-9 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-700   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                  <h2 className="text-2xl text-center sm:text-4xl text-white  font-bold title-font mb-3">
                    Clients
                  </h2>

                  <Link href={"/coustomers"}>
                    <div className=" flex justify-center mt-3 ">
                      <Image
                        src={"/images/trophy.png"}
                        width={90}
                        height={90}
                      ></Image>
                    </div>
                  </Link>
                </div>

                <div className=" xl:w-1/5 xl:py-12 lg:w-1/3 md:w-1/3 px-4 py-9 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-500   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                  <h2 className="text-2xl text-center sm:text-4xl text-white  font-bold title-font mb-3">
                    Projects
                  </h2>
                  <Link href={"/projects"}>
                    <div className=" flex justify-center mt-3 ">
                      <Image
                        src={"/images/project.png"}
                        width={90}
                        height={90}
                      ></Image>
                    </div>
                  </Link>
                </div>

                {viewRoles.value === "admin" && (
                  <div className=" xl:w-1/5 xl:py-12 lg:w-1/3 md:w-1/3 px-4 py-9 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-700   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                    <h2 className="text-2xl text-center sm:text-4xl text-white  font-bold title-font mb-3">
                      Teams
                    </h2>

                    <Link href={"/users"} className=" items-center">
                      <div className=" flex justify-center mt-3 ">
                        <Image
                          src={"/images/team.png"}
                          width={90}
                          height={90}
                        ></Image>
                      </div>
                    </Link>
                  </div>
                )}

                <div className=" xl:w-1/5 xl:py-10 lg:w-1/3 md:w-1/3 px-4 py-7 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-500   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                  <h2 className="text-2xl my-2 text-center sm:text-4xl text-white  font-bold title-font mb-3">
                    Message
                  </h2>
                  <Link href={"/reports"}>
                    <div className=" flex justify-center mt-3 ">
                      <Image
                        src={"/images/message.png"}
                        width={90}
                        height={90}
                      ></Image>
                    </div>
                  </Link>
                </div>
                <div className=" xl:w-1/5 xl:py-12 lg:w-1/3 md:w-1/3 px-4 py-9 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-700   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                  <h2 className="text-2xl text-center sm:text-4xl text-white  font-bold title-font mb-3">
                    Categorys
                  </h2>
                  <Link href={"/category"}>
                    <div className=" flex justify-center mt-3 ">
                      <Image
                        src={"/images/project.png"}
                        width={90}
                        height={90}
                      ></Image>
                    </div>
                  </Link>
                </div>
                <div className=" xl:w-1/5 xl:py-12 lg:w-1/3 md:w-1/3 px-4 py-9 mx-5  my-5  w-64 shadow-md shadow-slate-900  rounded-2xl bg-blue-500   hover:shadow-lg  hover:-translate-y-2  duration-500 hover:scale-105 border-opacity-60">
                  <h2 className="text-2xl text-center sm:text-4xl text-white  font-bold title-font mb-3">
                    Invoices
                  </h2>
                  <Link href={"/reports"}>
                    <div className=" flex justify-center mt-3 ">
                      <Image
                        src={"/images/message.png"}
                        width={90}
                        height={90}
                      ></Image>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    </>
  );
}
